modLoader="javafml"
loaderVersion="${loader_version_range}"
license="IALD"
[[mods]]
modId="ialdfufudoll"
version="1.1"
displayName="ialdfufudoll"
logoFile="icon.png"
authors="ialdaiaxiariyay"
description='''IALDGTCORE'''
[[dependencies.ialdfufudoll]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.ialdfufudoll]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"
